"""JSONBuilder — the PRD §8 call document, derived from the EventLog (M3 T5).

PRD §8: "Built deterministically from EventLog. Never generated by asking the
LLM to recall." This module is that determinism. It is a pure function over
(EventLog, CallState): no I/O, no clock, no network, so the same inputs always
produce the same document and it can be tested without a live call.

Division of labour between the two inputs, per the M3 plan's one-producer /
three-consumers design:

  * the EventLog supplies everything that *happened* — turns, their numbering,
    slot writes, handoffs, CSAT;
  * CallState supplies what was *captured* — caller identity, slot values,
    intents, the resolution the agents recorded.

Where the two could disagree the log wins, because the log is what the database
projection is also built from.

Fields owned by later milestones are emitted as empty or null, never omitted,
so the schema keeps one shape from M3 through M7 (M3 plan, Risks):
``compliance_flags`` and ``guardrail_events`` arrive with M6; ``latency`` and
``recording_url`` with M7.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from events import Event, EventLog, EventType
from state import CallState

#: Role names in the §8 transcript. The PRD says "user|agent" — note "agent",
#: not the "assistant" the framework uses internally.
ROLE_USER = "user"
ROLE_AGENT = "agent"


def _effective_time(event: Event) -> datetime:
    """When the turn actually happened, for conversational ordering.

    An interrupted assistant reply is only committed to the chat context when
    the *next* turn commits, so ``agent_turn`` events can arrive in the log
    after the user turn that cut them off (found during the M2 investigation).
    ``spoken_at`` records when the audio began; fall back to arrival time when
    it is absent.

    This mixes two sources — ``spoken_at`` from the framework's event clock and
    ``ts`` from the log's own — which is safe only because both are the same
    process clock, microseconds apart, in a live call. It is not safe for
    reconstructed logs: replaying real ``spoken_at`` values alongside freshly
    stamped ``ts`` values sorts every agent turn before every user turn. If a
    replay path is ever needed, the dump has to carry each event's ``ts`` so
    both sides come from one clock.
    """
    spoken_at = event.payload.get("spoken_at")
    if isinstance(spoken_at, str):
        try:
            return datetime.fromisoformat(spoken_at)
        except ValueError:
            pass
    return event.ts


def _turn_events_in_spoken_order(log: EventLog) -> list[Event]:
    turns = [e for e in log.events if e.turn_idx is not None]
    # Stable sort on effective time, so equal timestamps keep arrival order.
    return sorted(turns, key=_effective_time)


def _predominant_language(log: EventLog, state: CallState) -> Optional[str]:
    """The single §8 ``language`` for a call that may have code-switched.

    Deviation #6 keeps per-turn language matching rather than PRD §5's lock, so
    there is no one locked value to report. The most representative single
    answer is the language the customer used most, ties broken by first
    appearance — "most recent" would let one trailing word rename the call.
    """
    counts: dict[str, int] = {}
    for event in log.events:
        if event.type is EventType.USER_TURN:
            language = event.payload.get("language")
            if isinstance(language, str) and language:
                counts[language] = counts.get(language, 0) + 1
    if counts:
        first_seen = {lang: i for i, lang in enumerate(counts)}
        return max(counts, key=lambda lang: (counts[lang], -first_seen[lang]))
    # No language ever reached the log (e.g. console --text, which has no STT).
    return state.current_language or (state.languages_seen[0] if state.languages_seen else None)


def _flatten_slots(state: CallState) -> dict[str, Any]:
    """§8 ``slots``: a flat name -> value map of everything captured.

    Only resolved slots appear. An UNAVAILABLE slot maps to null — "we asked and
    there was nothing to give" is information, and dropping it would be
    indistinguishable from never having asked.
    """
    flat: dict[str, Any] = {}
    containers = [state.greet, state.router, state.wrap]
    containers += [getattr(state.slots, name) for name in type(state.slots).model_fields]
    for container in containers:
        for field_name in type(container).model_fields:
            slot = getattr(container, field_name)
            if slot.is_resolved:
                flat[field_name] = slot.value
    return flat


def _agent_name_at(log: EventLog, seq: int) -> str:
    """Which agent was active when the event at ``seq`` happened.

    Read from ``agent_handoff`` events, so it stays correct once T6 introduces
    Greet -> Wrap. Empty string before the first handoff: M3 pre-T6 runs a
    single unnamed agent, and inventing a name here would put something in the
    document that never happened.
    """
    current = ""
    for event in log.events:
        if event.seq >= seq:
            break
        if event.type is EventType.AGENT_HANDOFF:
            to = event.payload.get("to")
            if isinstance(to, str):
                current = to
    return current


def _slot_for_answer(log: EventLog, answer: Event) -> Optional[str]:
    """The slot this answer filled, if any.

    A ``slot_set`` appended after the answer and before the next turn is
    attributed to it. Yields None throughout M3 until T6 starts writing them.
    """
    after = [e for e in log.events if e.seq > answer.seq]
    for event in after:
        if event.turn_idx is not None:
            break  # reached the next turn; stop looking
        if event.type is EventType.SLOT_SET:
            name = event.payload.get("slot")
            if isinstance(name, str):
                return name
    return None


def _build_qa(log: EventLog) -> list[dict[str, Any]]:
    """Pair each agent question with the answer that followed it.

    ``turn_idx`` is the *answer's* number, not the question's: a qa entry exists
    because a customer answered, and the slot it records is the one their answer
    filled. The numbers themselves come from the log — this only selects among
    them, so turn numbering still lives in exactly one place.

    A user turn with no preceding question still produces an entry with an empty
    question (the customer spoke first). A trailing question with no answer
    produces nothing: an unanswered question is not a question-and-answer pair.
    See ``resolution`` for how that case is surfaced instead.
    """
    entries: list[dict[str, Any]] = []
    pending_question: Optional[Event] = None

    for event in _turn_events_in_spoken_order(log):
        if event.type is EventType.AGENT_TURN:
            pending_question = event
            continue

        answer_raw = str(event.payload.get("text") or "")
        entries.append(
            {
                "turn_idx": event.turn_idx,
                "agent": _agent_name_at(log, pending_question.seq if pending_question else event.seq),
                "question": str(pending_question.payload.get("text") or "") if pending_question else "",
                "answer_raw": answer_raw,
                # Real normalisation (digits to words, markup stripping) is the
                # M6 output filter's job; until then this is the identity.
                "answer_normalized": answer_raw.strip(),
                "slot": _slot_for_answer(log, event),
                "tool_calls": [],  # tool_call events have no producer until M4
                "ts": event.ts.isoformat(),
            }
        )
        pending_question = None

    return entries


def _has_unanswered_final_turn(log: EventLog) -> bool:
    """True when the customer spoke last and never got a reply.

    A real and expected shape: an LLM failure, a crash, a disconnect or a plain
    hangup all end a call this way (M3 plan, open item 2).
    """
    turns = _turn_events_in_spoken_order(log)
    return bool(turns) and turns[-1].type is EventType.USER_TURN


def _build_transcript(log: EventLog) -> list[dict[str, Any]]:
    return [
        {
            "role": ROLE_USER if event.type is EventType.USER_TURN else ROLE_AGENT,
            "agent": "" if event.type is EventType.USER_TURN else _agent_name_at(log, event.seq),
            "text": str(event.payload.get("text") or ""),
            "ts": _effective_time(event).isoformat(),
        }
        for event in _turn_events_in_spoken_order(log)
    ]


def _csat(log: EventLog) -> Optional[int]:
    """The rating from the log, which is authoritative over the wrap slot.

    The slot records *that* a rating was captured so the Wrap gate can close;
    the number itself lives here. Last one wins if a caller revises it.
    """
    value: Optional[int] = None
    for event in log.events:
        if event.type is EventType.CSAT_RECORDED:
            raw = event.payload.get("csat")
            if isinstance(raw, int):
                value = raw
    return value


def _resolution(log: EventLog, state: CallState) -> dict[str, Any]:
    status = state.resolution.status.value if state.resolution.status else None
    if status is None and _has_unanswered_final_turn(log):
        # M3 plan, open item 2: the customer's last turn went unanswered, so the
        # call did not reach a conclusion. "abandoned" is already in §8's enum;
        # a synthetic empty qa entry would instead assert an exchange that never
        # took place.
        status = "abandoned"
    return {
        "status": status,
        "summary": state.resolution.summary,
        "ticket_id": state.resolution.ticket_id,
    }


def _ended_at(log: EventLog) -> Optional[datetime]:
    for event in reversed(log.events):
        if event.type is EventType.CALL_ENDED:
            return event.ts
    return None


def build_call_json(log: EventLog, state: CallState) -> dict[str, Any]:
    """Build the PRD §8 document. Pure: same inputs, same output, no I/O."""
    ended_at = _ended_at(log)
    duration_s = int((ended_at - state.started_at).total_seconds()) if ended_at else None

    return {
        "call_id": state.call_id,
        "started_at": state.started_at.isoformat(),
        "ended_at": ended_at.isoformat() if ended_at else None,
        "duration_s": duration_s,
        "language": _predominant_language(log, state),
        "caller": {
            "name": state.caller.name,
            "phone": state.caller.phone,
            "customer_id": state.caller.customer_id,
        },
        "intents": [intent.value for intent in state.intents_handled],
        "qa": _build_qa(log),
        "slots": _flatten_slots(state),
        "resolution": _resolution(log, state),
        "csat": _csat(log),
        # --- owned by later milestones; emitted empty, never omitted ---
        "compliance_flags": [],  # M6
        "guardrail_events": [],  # M6
        "latency": {"avg_turn_ms": None, "p95_turn_ms": None},  # M7
        "recording_url": None,  # M7
        "transcript": _build_transcript(log),
    }
